spring:
  cloud:
    gateway:
      globalcors:
      corsConfigurations:
      '[/**]':
      allowedOrigins: "*"
      allowedMethods:
        - GET
        - POST
      routes:
        - id: r1
          uri: http://localhost:8282
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:8283
          predicates :
            - Path=/inventories/**
        - id: r3
          uri: http://localhost:8284
          predicates:
              - Path=/bills/**
        - id: r4
            uri: http://localhost:8284
            predicates:
              - Path=/fullBill/**